// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apple-iap.proto

package applerpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyReceiptResponse_Status int32

const (
	VerifyReceiptResponse_UNKNOWN_STATUS        VerifyReceiptResponse_Status = 0
	VerifyReceiptResponse_OK                    VerifyReceiptResponse_Status = 1
	VerifyReceiptResponse_REFUNDED              VerifyReceiptResponse_Status = 2
	VerifyReceiptResponse_SUBSCRIPTION_CANCELED VerifyReceiptResponse_Status = 3
)

var VerifyReceiptResponse_Status_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "OK",
	2: "REFUNDED",
	3: "SUBSCRIPTION_CANCELED",
}

var VerifyReceiptResponse_Status_value = map[string]int32{
	"UNKNOWN_STATUS":        0,
	"OK":                    1,
	"REFUNDED":              2,
	"SUBSCRIPTION_CANCELED": 3,
}

func (x VerifyReceiptResponse_Status) String() string {
	return proto.EnumName(VerifyReceiptResponse_Status_name, int32(x))
}

func (VerifyReceiptResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ff98ced1da323f3, []int{1, 0}
}

type VerifyReceiptResponse_Type int32

const (
	VerifyReceiptResponse_UNKNOWN_IAP_TYPE            VerifyReceiptResponse_Type = 0
	VerifyReceiptResponse_CONSUMABLE                  VerifyReceiptResponse_Type = 1
	VerifyReceiptResponse_NON_CONSUMABLE              VerifyReceiptResponse_Type = 2
	VerifyReceiptResponse_AUTO_RENEWABLE_SUBSCRIPTION VerifyReceiptResponse_Type = 3
	VerifyReceiptResponse_NON_RENEWING_SUBSCRIPTIONS  VerifyReceiptResponse_Type = 4
)

var VerifyReceiptResponse_Type_name = map[int32]string{
	0: "UNKNOWN_IAP_TYPE",
	1: "CONSUMABLE",
	2: "NON_CONSUMABLE",
	3: "AUTO_RENEWABLE_SUBSCRIPTION",
	4: "NON_RENEWING_SUBSCRIPTIONS",
}

var VerifyReceiptResponse_Type_value = map[string]int32{
	"UNKNOWN_IAP_TYPE":            0,
	"CONSUMABLE":                  1,
	"NON_CONSUMABLE":              2,
	"AUTO_RENEWABLE_SUBSCRIPTION": 3,
	"NON_RENEWING_SUBSCRIPTIONS":  4,
}

func (x VerifyReceiptResponse_Type) String() string {
	return proto.EnumName(VerifyReceiptResponse_Type_name, int32(x))
}

func (VerifyReceiptResponse_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ff98ced1da323f3, []int{1, 1}
}

type VerifyReceiptParams struct {
	Receipt              string                `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Password             *wrappers.StringValue `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VerifyReceiptParams) Reset()         { *m = VerifyReceiptParams{} }
func (m *VerifyReceiptParams) String() string { return proto.CompactTextString(m) }
func (*VerifyReceiptParams) ProtoMessage()    {}
func (*VerifyReceiptParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff98ced1da323f3, []int{0}
}

func (m *VerifyReceiptParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReceiptParams.Unmarshal(m, b)
}
func (m *VerifyReceiptParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReceiptParams.Marshal(b, m, deterministic)
}
func (m *VerifyReceiptParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReceiptParams.Merge(m, src)
}
func (m *VerifyReceiptParams) XXX_Size() int {
	return xxx_messageInfo_VerifyReceiptParams.Size(m)
}
func (m *VerifyReceiptParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReceiptParams.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReceiptParams proto.InternalMessageInfo

func (m *VerifyReceiptParams) GetReceipt() string {
	if m != nil {
		return m.Receipt
	}
	return ""
}

func (m *VerifyReceiptParams) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

type VerifyReceiptResponse struct {
	Status               VerifyReceiptResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pepeunlimited.apple.VerifyReceiptResponse_Status" json:"status,omitempty"`
	Type                 VerifyReceiptResponse_Type   `protobuf:"varint,2,opt,name=type,proto3,enum=pepeunlimited.apple.VerifyReceiptResponse_Type" json:"type,omitempty"`
	AppleProductId       string                       `protobuf:"bytes,3,opt,name=apple_product_id,json=appleProductId,proto3" json:"apple_product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *VerifyReceiptResponse) Reset()         { *m = VerifyReceiptResponse{} }
func (m *VerifyReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyReceiptResponse) ProtoMessage()    {}
func (*VerifyReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff98ced1da323f3, []int{1}
}

func (m *VerifyReceiptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReceiptResponse.Unmarshal(m, b)
}
func (m *VerifyReceiptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReceiptResponse.Marshal(b, m, deterministic)
}
func (m *VerifyReceiptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReceiptResponse.Merge(m, src)
}
func (m *VerifyReceiptResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyReceiptResponse.Size(m)
}
func (m *VerifyReceiptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReceiptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReceiptResponse proto.InternalMessageInfo

func (m *VerifyReceiptResponse) GetStatus() VerifyReceiptResponse_Status {
	if m != nil {
		return m.Status
	}
	return VerifyReceiptResponse_UNKNOWN_STATUS
}

func (m *VerifyReceiptResponse) GetType() VerifyReceiptResponse_Type {
	if m != nil {
		return m.Type
	}
	return VerifyReceiptResponse_UNKNOWN_IAP_TYPE
}

func (m *VerifyReceiptResponse) GetAppleProductId() string {
	if m != nil {
		return m.AppleProductId
	}
	return ""
}

func init() {
	proto.RegisterEnum("pepeunlimited.apple.VerifyReceiptResponse_Status", VerifyReceiptResponse_Status_name, VerifyReceiptResponse_Status_value)
	proto.RegisterEnum("pepeunlimited.apple.VerifyReceiptResponse_Type", VerifyReceiptResponse_Type_name, VerifyReceiptResponse_Type_value)
	proto.RegisterType((*VerifyReceiptParams)(nil), "pepeunlimited.apple.VerifyReceiptParams")
	proto.RegisterType((*VerifyReceiptResponse)(nil), "pepeunlimited.apple.VerifyReceiptResponse")
}

func init() { proto.RegisterFile("apple-iap.proto", fileDescriptor_7ff98ced1da323f3) }

var fileDescriptor_7ff98ced1da323f3 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0x28, 0x84, 0x01, 0xd2, 0xd5, 0x96, 0x4a, 0x21, 0x45, 0xa5, 0xca, 0x29, 0x42,
	0xc2, 0x11, 0xe1, 0xc2, 0xd5, 0x71, 0x0c, 0xb2, 0xda, 0xae, 0x2d, 0xaf, 0xdd, 0x0a, 0x2e, 0x96,
	0x1b, 0x4f, 0xa3, 0x95, 0x92, 0x78, 0xb5, 0x5e, 0x53, 0x72, 0xe4, 0x5f, 0xf8, 0x50, 0xe4, 0x35,
	0x01, 0x82, 0x2a, 0x41, 0x8f, 0xfb, 0xde, 0xbc, 0xf7, 0x66, 0x66, 0x07, 0x0e, 0x33, 0x29, 0x57,
	0xf8, 0x46, 0x64, 0xd2, 0x96, 0xaa, 0xd0, 0x05, 0x3d, 0x92, 0x28, 0xb1, 0xda, 0xac, 0xc4, 0x5a,
	0x68, 0xcc, 0x6d, 0x43, 0x0f, 0x4f, 0x96, 0x45, 0xb1, 0x5c, 0xe1, 0xc4, 0x94, 0xdc, 0x54, 0xb7,
	0x13, 0x5c, 0x4b, 0xbd, 0x6d, 0x14, 0xc3, 0xd3, 0xbf, 0xc9, 0x3b, 0x95, 0x49, 0x89, 0xaa, 0x6c,
	0xf8, 0x91, 0x80, 0xa3, 0x2b, 0x54, 0xe2, 0x76, 0x1b, 0xe1, 0x02, 0x85, 0xd4, 0x61, 0xa6, 0xb2,
	0x75, 0x49, 0x07, 0xf0, 0x48, 0x35, 0xc0, 0xc0, 0x3a, 0xb3, 0xc6, 0x8f, 0xa3, 0xdd, 0x93, 0xbe,
	0x87, 0x9e, 0xcc, 0xca, 0xf2, 0xae, 0x50, 0xf9, 0xa0, 0x75, 0x66, 0x8d, 0x9f, 0x4c, 0x5f, 0xda,
	0x4d, 0x86, 0xbd, 0xcb, 0xb0, 0xb9, 0x56, 0x62, 0xb3, 0xbc, 0xca, 0x56, 0x15, 0x46, 0xbf, 0xaa,
	0x47, 0xdf, 0xdb, 0x70, 0xbc, 0x97, 0x15, 0x61, 0x29, 0x8b, 0x4d, 0x89, 0xd4, 0x87, 0x6e, 0xa9,
	0x33, 0x5d, 0x95, 0x26, 0xac, 0x3f, 0x7d, 0x6b, 0xdf, 0x33, 0xa7, 0x7d, 0xaf, 0xd6, 0xe6, 0x46,
	0x18, 0xfd, 0x34, 0xa0, 0x2e, 0x74, 0xf4, 0x56, 0xa2, 0x69, 0xad, 0x3f, 0x9d, 0x3c, 0xc0, 0x28,
	0xde, 0x4a, 0x8c, 0x8c, 0x98, 0x8e, 0x81, 0x98, 0xca, 0x54, 0xaa, 0x22, 0xaf, 0x16, 0x3a, 0x15,
	0xf9, 0xa0, 0x6d, 0xd6, 0xd0, 0x37, 0x78, 0xd8, 0xc0, 0x7e, 0x3e, 0xba, 0x84, 0x6e, 0xd3, 0x00,
	0xa5, 0xd0, 0x4f, 0xd8, 0x39, 0x0b, 0xae, 0x59, 0xca, 0x63, 0x27, 0x4e, 0x38, 0x39, 0xa0, 0x5d,
	0x68, 0x05, 0xe7, 0xc4, 0xa2, 0x4f, 0xa1, 0x17, 0x79, 0x1f, 0x12, 0x36, 0xf7, 0xe6, 0xa4, 0x45,
	0x5f, 0xc0, 0x31, 0x4f, 0x66, 0xdc, 0x8d, 0xfc, 0x30, 0xf6, 0x03, 0x96, 0xba, 0x0e, 0x73, 0xbd,
	0x0b, 0x6f, 0x4e, 0xda, 0xa3, 0x6f, 0x16, 0x74, 0xea, 0x3e, 0xe8, 0x73, 0x20, 0x3b, 0x37, 0xdf,
	0x09, 0xd3, 0xf8, 0x53, 0xe8, 0x91, 0x03, 0xda, 0x07, 0x70, 0x03, 0xc6, 0x93, 0x4b, 0x67, 0x76,
	0xe1, 0x11, 0xab, 0xce, 0x64, 0xb5, 0xc1, 0x6f, 0xac, 0x45, 0x5f, 0xc1, 0x89, 0x93, 0xc4, 0x41,
	0x1a, 0x79, 0xcc, 0xbb, 0xae, 0xb1, 0xf4, 0xcf, 0x30, 0xd2, 0xa6, 0xa7, 0x30, 0xac, 0x45, 0x86,
	0xf7, 0xd9, 0xc7, 0x3d, 0x9a, 0x93, 0xce, 0xf4, 0x2b, 0x1c, 0x3a, 0xf5, 0x90, 0xbe, 0x13, 0x72,
	0x54, 0x5f, 0xc4, 0x02, 0x29, 0xc2, 0xb3, 0xbd, 0x9d, 0xd1, 0xf1, 0xbf, 0xf7, 0xda, 0x1c, 0xd2,
	0xf0, 0xf5, 0xff, 0xff, 0xc0, 0x0c, 0x3e, 0xf7, 0x0c, 0xad, 0xe4, 0xe2, 0xa6, 0x6b, 0x8e, 0xe9,
	0xdd, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x56, 0x3a, 0x7a, 0x03, 0x03, 0x00, 0x00,
}
