// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apple-iap.proto

package appleiap

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyReceiptParams struct {
	Receipt              string                `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Password             *wrappers.StringValue `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VerifyReceiptParams) Reset()         { *m = VerifyReceiptParams{} }
func (m *VerifyReceiptParams) String() string { return proto.CompactTextString(m) }
func (*VerifyReceiptParams) ProtoMessage()    {}
func (*VerifyReceiptParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff98ced1da323f3, []int{0}
}

func (m *VerifyReceiptParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReceiptParams.Unmarshal(m, b)
}
func (m *VerifyReceiptParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReceiptParams.Marshal(b, m, deterministic)
}
func (m *VerifyReceiptParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReceiptParams.Merge(m, src)
}
func (m *VerifyReceiptParams) XXX_Size() int {
	return xxx_messageInfo_VerifyReceiptParams.Size(m)
}
func (m *VerifyReceiptParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReceiptParams.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReceiptParams proto.InternalMessageInfo

func (m *VerifyReceiptParams) GetReceipt() string {
	if m != nil {
		return m.Receipt
	}
	return ""
}

func (m *VerifyReceiptParams) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

type VerifyReceiptResponse struct {
	//    enum Status {
	//        UNKNOWN_STATUS          = 0;
	//        OK                      = 1;
	//        REFUNDED                = 2;
	//        SUBSCRIPTION_CANCELED   = 3;
	//    }
	//    enum Type {
	//        UNKNOWN_IAP_TYPE            = 0;
	//        CONSUMABLE                  = 1;
	//        NON_CONSUMABLE              = 2;
	//        AUTO_RENEWABLE_SUBSCRIPTION = 3;
	//        NON_RENEWING_SUBSCRIPTIONS  = 4;
	//    }
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AppleProductId       string   `protobuf:"bytes,3,opt,name=apple_product_id,json=appleProductId,proto3" json:"apple_product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReceiptResponse) Reset()         { *m = VerifyReceiptResponse{} }
func (m *VerifyReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyReceiptResponse) ProtoMessage()    {}
func (*VerifyReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff98ced1da323f3, []int{1}
}

func (m *VerifyReceiptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReceiptResponse.Unmarshal(m, b)
}
func (m *VerifyReceiptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReceiptResponse.Marshal(b, m, deterministic)
}
func (m *VerifyReceiptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReceiptResponse.Merge(m, src)
}
func (m *VerifyReceiptResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyReceiptResponse.Size(m)
}
func (m *VerifyReceiptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReceiptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReceiptResponse proto.InternalMessageInfo

func (m *VerifyReceiptResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VerifyReceiptResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VerifyReceiptResponse) GetAppleProductId() string {
	if m != nil {
		return m.AppleProductId
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyReceiptParams)(nil), "pepeunlimited.apple.VerifyReceiptParams")
	proto.RegisterType((*VerifyReceiptResponse)(nil), "pepeunlimited.apple.VerifyReceiptResponse")
}

func init() { proto.RegisterFile("apple-iap.proto", fileDescriptor_7ff98ced1da323f3) }

var fileDescriptor_7ff98ced1da323f3 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xa9, 0x4a, 0x6d, 0x47, 0xb4, 0xb2, 0x45, 0x09, 0x51, 0xa4, 0xf4, 0x14, 0x04, 0xb7,
	0x50, 0x2f, 0x5e, 0xeb, 0xad, 0xb7, 0x90, 0x42, 0x0f, 0x5e, 0xca, 0x36, 0x99, 0x86, 0x85, 0x24,
	0x3b, 0xcc, 0x6e, 0xac, 0xf9, 0xf7, 0xe2, 0xa6, 0x11, 0x2a, 0x05, 0x6f, 0x3b, 0xef, 0xbd, 0xe5,
	0x9b, 0x79, 0x30, 0x52, 0x44, 0x05, 0xbe, 0x68, 0x45, 0x92, 0xd8, 0x38, 0x23, 0xc6, 0x84, 0x84,
	0x75, 0x55, 0xe8, 0x52, 0x3b, 0xcc, 0xa4, 0xb7, 0xc3, 0x87, 0xdc, 0x98, 0xbc, 0xc0, 0x99, 0x8f,
	0x6c, 0xeb, 0xdd, 0x0c, 0x4b, 0x72, 0x4d, 0xfb, 0x23, 0x7c, 0xfa, 0x6b, 0xee, 0x59, 0x11, 0x21,
	0xdb, 0xd6, 0x9f, 0x6a, 0x18, 0xaf, 0x91, 0xf5, 0xae, 0x49, 0x30, 0x45, 0x4d, 0x2e, 0x56, 0xac,
	0x4a, 0x2b, 0x02, 0xb8, 0xe4, 0x56, 0x08, 0x7a, 0x93, 0x5e, 0x34, 0x4c, 0xba, 0x51, 0xbc, 0xc1,
	0x80, 0x94, 0xb5, 0x7b, 0xc3, 0x59, 0x70, 0x36, 0xe9, 0x45, 0x57, 0xf3, 0x47, 0xd9, 0x32, 0x64,
	0xc7, 0x90, 0x2b, 0xc7, 0xba, 0xca, 0xd7, 0xaa, 0xa8, 0x31, 0xf9, 0x4d, 0x4f, 0x4b, 0xb8, 0x3b,
	0x42, 0x25, 0x68, 0xc9, 0x54, 0x16, 0xc5, 0x3d, 0xf4, 0xad, 0x53, 0xae, 0xb6, 0x07, 0xd6, 0x61,
	0x12, 0x02, 0x2e, 0x5c, 0x43, 0xe8, 0x31, 0xc3, 0xc4, 0xbf, 0x45, 0x04, 0xb7, 0xfe, 0xea, 0x0d,
	0xb1, 0xc9, 0xea, 0xd4, 0x6d, 0x74, 0x16, 0x9c, 0x7b, 0xff, 0xc6, 0xeb, 0x71, 0x2b, 0x2f, 0xb3,
	0xf9, 0x17, 0x8c, 0x16, 0x3f, 0xca, 0x72, 0x11, 0xaf, 0x90, 0x3f, 0x75, 0x8a, 0x02, 0xe1, 0xfa,
	0x68, 0x03, 0x11, 0xc9, 0x13, 0x85, 0xca, 0x13, 0x85, 0x84, 0xcf, 0xff, 0x27, 0xbb, 0x7b, 0xde,
	0xe1, 0x63, 0xe0, 0x6d, 0xa6, 0x74, 0xdb, 0xf7, 0xa5, 0xbc, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xe5, 0xbc, 0x0e, 0x8d, 0xcb, 0x01, 0x00, 0x00,
}
